version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - database_url=postgres://user:password@postgres:5432/db
    command: bash -c "poetry run python3 src/app/main.py"
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"